jung-kurt/gofpdf

fpdf.go, fpdf_test.go
Multi-segment path drawing:
- MoveTo
- LineTo
- CurveTo
- CurveBezierCubicTo
- ClosePath
- DrawPath
See tutorial 29 for a demonstration.
=> Added path drawing methods

.gitignore, fpdf.go, util.go
I have an example which I will add later.
=> implement line join style

doc.go, fpdf.go, fpdf_test.go
Thanks in advance for merging!
=> Implement ArcTo and tutorial for line join style

fpdf.go
=> Fix SetFontUnitSize name so that we can build

def.go, fpdf.go
This has been tested successfully with draw2d.
Fixes #29
=> Implement GetAlpha

fpdf_test.go
Another small change to make tests pass in Windows.
=> Windows testing 2

contrib/barcode/barcode.go
This adds support for Pdf417 barcodes using https://github.com/ruudk/golang-pdf417 :)
=> Add support for Pdf417 barcodes

fpdf.go
=> fpdf: typo

fpdf.go
Hello,
I'm adding a support of CMYK color in func parserjpg.
=> Adding support CMYK in parsejpg

contrib/barcode/barcode.go
to prevent race condition (issue #84)
=> added mutex to barcode cache

fpdf.go
=> Added A1 and A2 page sizes

contrib/barcode/barcode.go, contrib/barcode/barcode_test.go
This adds support for Aztec barcodes from @boombuler in https://github.com/boombuler/barcode/issues/10
=> Add support for Aztec barcodes

font.go, fpdf.go, util.go
Also see https://github.com/mvdan/interfacer and https://www.reddit.com/r/golang/comments/5t09v5/writing_from_gonumplot_to_gofpdf_package_directly/ddm7rmm/
=> Accept interfaces where appropriate.

def.go, fpdf.go, fpdf_test.go
I've been using the gofpdf library for a while now and it's so useful! 
I recently found the need to have a PDF print itself automatically on open using JavaScript. This PR is an almost verbatim re-implementation of [this FPDF extension](http://www.fpdf.org/en/script/script36.php).
I’d love to hear any feedback you might have.
=> add the ability to include JavaScript in PDFs

fpdf.go
Add "Tabloid" page size, 11 x 17 inches according to ANSI X3.151.
=> Add "Tabloid" page size

fpdf.go, template.go
Replace with strings.Contains
Before:
if strings.Index(x, y) != -1 {}
After:
if strings.Contains(x, y) {}
=> Replace strings.Index with strings.Contains

def.go, fpdf.go, fpdf_test.go
=> [125] Added generic alias-replacement function to enable Table of Contents functionality

fpdf.go, fpdf_test.go
=> Make SplitLines and MultiCell split at the same place

.gitignore, def.go, fpdf.go, fpdf_test.go, ttfparser_test.go
Allows user to navigate through PDF document by changing the current page to the desired page if it's valid.
=> Change current page of PDF document.

fpdf.go, fpdf_test.go
=> Remove additional graphics state checks

fpdf.go, fpdf_test.go
I wanted the ability to insert images retrieved as binary (not existing locally). I wasn't sure if you wanted to be able to verify that the image is the correct extension before registering but this will be very useful to me. This is my first attempt contributing to an open-source project. Please be gentle.
=> added imageoptionsreader

fpdf.go
Change-Id: Ieaacbf19acfce1e776eccbfa3bbc030a2ab93d5f
=> improve the speed of MultiCell

def.go, fpdf.go, fpdf_test.go, internal/example/example.go, ttfparser_test.go
copied implementation of "underline" and set the line a little bit higher: text is striked-out
=> Strikeout: use "S" as styleStr

fpdf.go, fpdf_test.go
Hi !
This PR extends the support for rounded rectangles by allowing different radius for each corner.
Two public methods are added : `RoundedRect2()` and `ClipRoundedRect2()`
It also rewrites the underlying code : the logic shared between both methods is extracted in `roundedRectPath()`, to avoid code duplication.
Any comments are welcomed; in particular, the names of the new methods could probably be more explicit. 
Thanks in advance for the review !
Benoit K.
=> Extends support for rounded rectangles
