jung-kurt/gofpdf

def.go
fpdf.go
util.go

This pull request adds two features to the Fpdf document generator:
You can configure a dash pattern in the graphics state using `SetDashPattern()`. Example: 
```
// Draw a dashed line with a 0.2mm black / 0.4mm white pattern. 
// Dash patterns are explained on page 217 of the Adobe PDF Reference 1.7: 
// http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf 
pdf.SetDashPattern([]float64{0.2, 0.4}, 0) 
pdf.Line(10, 10, 200, 10) 
```
With `SetFontLoader()` you can add a font loader that is used whenever Fpdf needs to load a .json or .z font file. The font loader is supposed to return an `io.Reader` for the requested file. If it returns an error instead Fpdf tries to load the font file from the specified font folder (`SetFontLocation()`).
Example:
```
type …
```

Dash line pattern and font loader extensions

---

fpdf_test.go

I had difficulty associating the filenames of the generated pdf's with their corresponding godoc examples. So I renamed the output filenames to correspond with the godoc names:
```
addpage.pdf -> Fpdf_AddPage.pdf
```
If the example had a broader meaning, I added the previous output name to the method.
For example:
```
fill.pdf -> Fpdf_DrawPath_fill.pdf
```
So now it is very easy to find back the output of a godoc example.

synchronize file names example pdf files with godoc

---

fpdf_test.go

I had difficulty reading examples on godoc as some lines are too long and require horizontal scrolling in textareas as apart of them is hidden. So I splitted the too long lines into two lines.

fix long lines in documentation examples

---

.gitignore
def.go
fpdf.go
fpdf_test.go

First Fpdf.GetFontDesc was added to access publicly the font descriptor. Afterwards support for baseline alignment ("A") was added to CellFormat. The example CellFormat_2 has been updated. For proper test coverage it was necessary to include the use of a custom font in this example. 
Fixes #24.
PS Would you mind to add me as collaborator? You can contact me through gmail:spe.stani.be if you like to discuss this first.
https://help.github.com/articles/how-do-i-add-a-collaborator

Implement vertical baseline alignment for text

---

def.go
doc.go
fpdf.go
fpdf_test.go
template.go
template_impl.go
util.go

Implementation of templating in the style of [FPDF_TPL](http://manuals.setasign.com/fpdi-manual/the-fpdf-tpl-class/). There are two parts to this: a `Template` interface and a specific implementation `FpdfTpl`. It diverges from the PHP original in that the method `Fpdf.CreateTemplate` uses a callback in which you write the template and then returns a read-only template, which should help ensure type safety and should avoid confusion.
The interface allows other code to insert templates by other mechanisms; the intention is to eventually use this to implement the document-reading functionality of [FPDI](http://manuals.setasign.com/fpdi-manual/the-fpdi-class/). It may have other uses, such as a mechanism for reading SVGs?
Also, I added a few more util methods that I needed, and that may …

Templating

---

fpdf_test.go

The tests currently don't pass on Windows because of a silly little thing:
```
--- FAIL: ExampleFpdf_MoveTo (0.00s)
got:
Successfully generated pdf\Fpdf_MoveTo_path.pdf
want:
Successfully generated pdf/Fpdf_MoveTo_path.pdf
```
etc for all the tests. This tiny change allows the tests to pass.

Allow the tests to work on Windows

---

contrib/barcode/barcode.go
contrib/barcode/barcode_test.go
fpdf.go

This uses https://github.com/boombuler/barcode to put barcodes on the PDF page.
I've opted for the same approach as with images, where you register a barcode and then use the same identifier to put it on the page later on. This has the same benefit that we can re-use the barcode multiple times later on.
The only downside I see with this approach is that when you put a barcode on (type Code128 for example) with a code, and then another barcode (Type EAN13 for example) with the exact same code, the Code128 barcode will get overwritten. This concern is not only limited to the `barcodes` map, but will also be a concern for the `Fpdf.images` map.
@jung-kurt I have noticed a small issue with the internal package tests with this. If I run `go test contrib/barcode/barcode_test.go` all tests (of …

Barcode contribution package.

---

contrib/barcode/barcode.go
contrib/httpimg/httpimg.go

Instead of forcing the type to be of gofpdf.Fpdf, we now use an
interface which could be whatever structure we want. This is useful for
third party libraries where they can define their own interface for the
PDF generator but still use these contribution packages.
Now external packages can implement their own PDF interface which
implements these methods and pass that along. Earlier, they would get
a type error.

Contribution packages specific interfaces.

---

fpdf.go
fpdf_test.go
htmlbasic.go

WriteAligned allows a user to write a single string and align it.
Previously, Write() would only write with Left alignment. Sometimes, you
want to align a specific text string to the center or the right.
HTMLBasic: add `<center>` tag.
This allows a user to center text within the HTML block. This way they
do not have to split up their input.
A new line will be created automatically before and after the centered
text.

Fpdf: add WriteAligned.

---

compare.go

All the "magic" of reference comparison happens within the
`CompareBytes` function.
Reading a file (with `ioutil.ReadFile`) gives you an array of bytes and
gofpdf supports writing to a byte buffer, where we can easily get the
bytes from.
Exporting `CompareBytes` would make it possible to use this core
functionality instead of having to convert the data into `io.Reader`.

Compare: make `CompareBytes` exported.

---

def.go
fpdf.go

Addresses #66. Adds the ability to support reading dpi from PNG images, and setting
dpi on any image directly; this allows images to be displayed at the
designed size.
This PR provides backwards-compatible support for reading DPI from images that support it, and for setting DPI manually and then having it properly taken into account when calculating image size.
The changes could have been much simpler except for backwards compatibility. There were two major problems:
* The parameters for the Image call. The system uses 96 dpi if the w/h parameters to Image are 0,0, but the assumption in the calculation of `ImageInfoType.Width()`, etc is 72. The only way I've come up with to preserve both is to use w/h parameters of -1 to mean "use the dpi stored in the ImageInfoType". This kind of sucks …

Support reading and/or setting image dpi

---

contrib/barcode/barcode.go
contrib/barcode/barcode_test.go

I came across this bug when I tried to create a Code 128 barcode for non-ascii-128 string: The framework panics because the barcode it tries to register is `nil`.
I think this is a reasonable way of dealing with the bug, but @jelmersnoeck might know more, as it looks like he contributed to this file.

prevent panic when registering barcode fails

---

def.go
fpdf.go

This PR adds a new function `SetXmpMetadata(xmpStream []byte)` to the API which allows the caller to insert a `/Type /Metadata /Subtype /XML` stream into the PDF file on output.
Then contents of the metadata stream must be a valid XMP metadata packet in XML format. It's up to the caller to generate such a packet, e.g. by using a library like http://github.com/echa/go-xmp. However, SetXmpMetadata does not perform any validity checks to keep the implementation lean.
I couldn't find a way to make this work with the existing API using the RawWrite* functions since they cannot be called during output (`Fpdf.enddoc()` writes PDF header, contents and trailer in one go).

Ability to write XMP Metadata

---

compare.go
internal/example/example.go

Currently diffs between different PDFs are printed to stdout. This is annoying, especially if the PDFs are quite large. The output is kind of useless anyway. Added a flag to enable/disable this behavior.

Added flag to print PDF byte diffs

---

def.go
fpdf.go
fpdf_test.go

As a new user I'd prefer to have page orientations available as consts, so that it's easier for me to get started. Also, I moved `strings.ToLower(..)` call on `orientationStr` to the top of the function so that you don't _lowerize_ a default value, and the sanitization in a single place.

Add consts for page orientations

---

contrib/barcode/barcode.go
contrib/barcode/barcode_test.go

This PR solves two problems I was having. First, I didn't know the printed size of a barcode on the PDF. Second, the barcodes printed on the PDF were scaling much too unpredictably. 
Barcode scaling works better for some kinds of barcodes than others. It would be possible using the new function to get the printed size of the barcode and use that as the scaling width. However, this solution would be subject to float arithmetic errors which could be disastrous if the unscaled width is just decimals below the minimum width necessary (see line 113 of scaledbarcode.go in boombuler/barcode). 
It seems reasonable to offer barcode scaling as an option. I suggest an implementation in this PR using pointers as optionals, a common Go practice. Happy to defer to you @jung-kurt on whether you want a …

make barcode scaling optional, provide a method to get unscaled barcode dimensions

---

fpdf.go

When CatalogSort is enabled, the sort.Strings routine is used to order
the "keys" used for the various objects being put into the PDF. Use
sort.SliceStable instead, and specify a function Less function that, if
possible, uses an attribute of the objs being sorted. This is more
deterministic.

sort the objs in the output more consistently

---

fpdf.go

While you're using a reader for i.e. an image you'll receive an EOF from go's io package which leads to pdf creation error

EOF error when using reader

---

fpdf.go

Add public wrapper "GetPageSizeStr" of private method
Having GetPageSizeStr public is useful for having the correct SizeType (properly scaled).
Also, that SizeType can be used to call AddPageFormat(..)

Added public wrapper "GetPageSizeStr" of private method

---

contrib/barcode/barcode.go

This allows arbitrary barcode scaling, rather than whole multiple
as required by github.com/boombuler/barcode

barcode: Scale via the PDF rather than the barcode library

---

template.go
template_impl.go

The only issue is the CreateTemplate function has to be depricated as it doesn't have an orientation.... I created a CreateTpl function that allows a non Fpdf instantiated Tpl to be created without flipping the orientation. I made sure the broken functionality of CreateTemplate stays in place... You can decide how to handle the backwards compatibility there

orientation of a template is now defined by the parent document.

---

def.go
fpdf_test.go
template.go
template_impl.go

Not sure if you want to pull this in, but it makes the default FpdfTpl serialize-able using gob. This allows an external package to save a template to memory or a file and turn it back into a template.
The one issue is all templates within a template are assumed to also be FpdfTpl objects. Considering the interface Tpl is public it would allow a user to create an external struct that implements Tpl that could not be a child of a FpdfTpl object.
Also there may be a better way to do this using reflection that wouldn't need to be updated in the event more properties are added to the FpdfTpl and ImageInfoType structs. Although I'm not sure that is possible considering they are non exported fields.
Anyway, figured I would send this your way too.

Added Ability to turn template into a byte string

---

def.go
fpdf.go

Added a new method `SetPageBox(t string, pb PageBox)` which allows you to add an art, crop, bleed and trim box to the document. The method applies the box type to the current page as well as the default. When a new page is added, all the default boxes are applied to the page. I considered adding pageboxes as a parameter when creating a new Fpdf object, but figured it would be better not to break the api.
A PageBox struct is just a PointType and a SizeType combined.

Added page boxes

---

fpdf_test.go
template.go
template_impl.go

Templates are now aware of the number of pages they have. The main additions are the FromPage and FromPages methods which allow you to extract a Template from a template if you pass in the page number. It follows the same page mechanism as FPDF where pages start in the index 1.
Needs tests.

Added the ability to have multiple pages in a template

---

def.go
fpdf.go
template.go
template_impl.go

- Updated Encode and Decode to ensure templates and images are pointers to the original objects
- Refactored so encoding no longer has to create p and o labels for images
- removed id from template and generate it using Bytes instead.

Refactored Encode and Decode functions, Fixed Template ID Conflicts

---

fpdf.go

width has already been reduced by left and right margin, so right margin doesn't need to be subtracted twice

Fix right alignment

---

def.go
fpdf.go

Currently, to change just the font style in user code, you have to do something like this:
````
pdf.SetFont("", "B", 0)
````
Now you can do:
````
pdf.SetFontStyle("B")
````
This implementation simply calls the exported `SetFont()` method internally. This differs slightly to `SetFontSize()`, which updates internal state and writes to the PDF in its own method. Let me know if you have any preference, or if I've missed anything.
Thanks.

Add SetFontStyle method

---

def.go
fpdf.go

This allows v2 of gofpdf to use gofpdi free pdf document importer.  The code that calls gofpdi is in the jung-kurt/gofpdfcontrib repository.

Add support for imported objects and templates for gofpdf v2

---

fpdf.go

With recent utf-8 support it is somewhat forgotten to add already defined font base dir. This fix is not backward compatible with already committed code in master.
pdf := gofpdf.NewCustom(&gofpdf.InitType{
UnitStr: "mm",
Size: gofpdf.SizeType{
Wd: 100,
Ht: 62,
},
FontDirStr: "./gofpdf/font",
})
pdf.AddUTF8Font("TimesNewRoman", "", "Times_New_Roman.ttf")
pdf.AddUTF8Font("TimesNewRoman", "B", "Times_New_Roman_Bold.ttf")
pdf.AddUTF8Font("TimesNewRoman", "I", "Times_New_Roman_Italic.ttf")
pdf.AddUTF8Font("TimesNewRoman", "BI", "Times_New_Roman_Bold_Italic.ttf")`
The code above didn't load fonts properly but with this fix code above will work.

Fix for not concating already defined filepath

---

contrib/barcode/barcode.go
contrib/barcode/barcode_test.go

This fixes an issue with barcode scaling that limited
barcode sizes to integer multiples of the pdf's unit.

maintain precision of desired w & h of barcodes

---

fpdf.go
go.mod
go.sum

Remove an unnecessary array copy. Improves performance from O(n^2) to O(n).
This assumes that each byte corresponds 1-1 to a rune.

Improve write performance

---

fpdf.go

UTF8 text splitted correctly by SplitText function in WriteAligned
method:
https://github.com/jung-kurt/gofpdf/blob/3aaf0b1a66c0ab02d925917376898a5856061d59/fpdf.go#L2811
Then, lines of text are written via Write function, and if text is
already wrapped by given width it will be printed using 'last chunk' case:
https://github.com/jung-kurt/gofpdf/blob/3aaf0b1a66c0ab02d925917376898a5856061d59/fpdf.go#L2747-L2754
But in this case, gofpdf does not move cursor to the next cell, which
cause all text to be printed on the same line without actual wrapping.
This commit makes workaround for it by explicitly setting right margin
to force automatic line break case:
https://github.com/jung-kurt/gofpdf/blob/3aaf0b1a66c0ab02d925917376898a5856061d59/fpdf.go#L2705-L2706

fix utf8 text wrapping

---

contrib/gofpdi/gofpdi.go
go.mod
go.sum

Updates contrib/gofpdi from v1.0.3 to v1.0.7
* imports pdf documents from any io.ReadSeeker
* exposes page sizes of imported pdf documents
@phpdave11 Thanks again for your quick release. I hope this PR meets with your approval.

update contrib/gofpdi from v1.0.3 to v1.0.7

---

def.go
fpdf.go

This allows changing or removing the PDF producer string in the metadata of the PDF file.
I assume this will influence https://github.com/jung-kurt/gofpdf/issues/177#issue-318671952

Add method `SetProducer`

---

contrib/gofpdi/gofpdi.go
contrib/gofpdi/gofpdi_test.go

Proposal to allow multiple independent Importer instances. Notably, this should improve concurrent use of the library.
* wraps Importer from `gofpdi` library in a simple struct
* allow users to obtain multiple Importer instances
* keep a default Importer for backwards compatibility
* add package level comment
This PR is based on an idea by @ayvan - see https://github.com/jung-kurt/gofpdf/pull/269 for comparison - but includes recent additions and does not include a `gofpdiPdf` member in the wrapper struct, thus making it easier to retain backwards compatibility without too much code duplication.
@ayvan, @phpdave11 For your information. And please feel free to suggest better approaches or different wordings for the comments.

contrib/gofpid: wrap Importer

---

fpdf.go
splittext.go
util.go

In English, a word should not be split into two lines, but Chinese words can be made into two lines.
I fixed this Bug mentioned in [issue](https://github.com/jung-kurt/gofpdf/issues/276).

fix split line bug

---

def.go
fpdf.go

Currently, it's possible to end up with the same image inserted into the final PDF multiple times. 
This is possible if you register the same image under two different keys (unlikely), but it's also possible when trying to use the same image in multiple templates. The [CreateTemplate example](https://github.com/jung-kurt/gofpdf/blob/5336f2c016d4b1b5e9399a84aa4657d374dd5cb3/fpdf_test.go#L2052) actually attempts this and the image is written into the PDF twice. After this  
change the filesize is reduced by about 20%.
It accomplishes this by storing the SHA-1 hash of each inserted image, and re-uses the objects ID if it's found. I've also committed my comments in a bunch of places from trying to understand the codebase.

Prevent image duplication

---

def.go
fpdf.go
template.go
template_impl.go

(Based upon #296, please review that one first!)
This allows templates derived from the principal struct (`pdf.UseTemplate()` or `pdf.UseTemplateScaled()`) to inherit the parents images list. They'll be available using the same key to facilitate image re-use.
As inheritance happens with the loaded fonts and [many other settings](https://github.com/jung-kurt/gofpdf/blob/ced1e15bca902f15732b6380aaa4bdc419d87eac/template_impl.go#L278), I think images would be expected too. Due to my other PR, this shouldn't increase the final PDF size.
This one however is a ⚠️ **breaking change** ⚠️. Consider the following scenario...
1. An image is registered in the main pdf `pdf.RegisterImageReader("myKey" ...)`
2. A new template is derived using `pdf.CreateTemplate()`
3. An image being registered in the …

 Initialize derived templates with parent images

---

fpdf.go

Fix for https://github.com/jung-kurt/gofpdf/issues/307
Tested on this code: 
```
pdf := gofpdf.New("P", "mm", "A5", "")
pdf.AddUTF8Font("HAN NOM A", "", "hn.ttf")
pdf.SetFont("HAN NOM A", "", 16)
pdf.AddPage()
pdf.Bookmark("1段落", 1, -1)
pdf.Cell(0, 6, "2段落")
pdf.Ln(50)
pdf.AddPage()
fileStr := example.Filename("Fpdf_Bookmark")
err := pdf.OutputFileAndClose(fileStr)
example.Summary(err, fileStr)
// Output:
// Successfully generated pdf/Fpdf_Bookmark.pdf
```
Result PDF:
I was unable to find ttf version of the font in original issue so used different one, but I think it won't be a problem.

fix utf16 in bookmarks

---

fpdf.go

This follows section 9.3.6 of the PDF32000_2008 specification.
I use this to create "invisible" text for overlaying on images, to make searchable PDFs from OCR results.
I also made a variant branch of this with consts for the different possible modes, addtextrenderingmode-withconsts. I wasn't sure which would be a more fpdf way of doing it, so made both versions.

Add SetTextRenderingMode function

---

fpdf_test.go
utf8fontfile.go

This my `worsefix` branch renamed, after reflecting I believe this is the correct way to fix it as it removes any side effects from the `splice` and `assembleTables` functions in `utf8fontfile.go` in addition I added a test `TestIssue0316`, if you back out the previous fix by changing all instances of `ReadLikeCopy` to just `Read` you can see the test fails, if you return them or apply this branch then the test passes. 
I did go through and check for any other instances of append modifying the underlying arrays. There were a couple I thought might be an issue but once I sat down to inspect them I was able to confirm they were working only on new arrays.

Issue316 copy changes

---

attachments.go
def.go
fpdf.go
fpdf_test.go

Hi, 
This PR adds support for embedded files, both at the root level via `SetAttachments()` or as page annotations via `AddAttachmentAnnotation()`. 
Summary of the changes :
- The main content is in attachments.go 
- A new type `Attachment` is added as an API convenience, and two internals slices are added (`attachments`  and `pageAttachments`). 
- The exported method Embed() (on Attachment) allows re-use of the same content for several annotations, without duplications.
- File annotations require to write an object before writing the page dict. Thus putpages() is slightly modified : the assumption on object number for /Kids in putpages() would otherwise failed. 
- Two examples are added.
Best,
BK

Add support for embedded files
